language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- export GRADLE_BUILD_DIR="build/libs"
- export TAG=$(git describe --abbrev=0 --tags)
- export MOD_TAG=${TAG#"v"}
- export RELEASE_PKG_FILE="${GRADLE_BUILD_DIR}/LongWaveRadiationBalance-${MOD_TAG}.jar"
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
- gradle -PprojVersion=$MOD_TAG build
deploy:
  provider: releases
  api_key:
    secure: sQpmYfShLzkWLHteJyhB4q0Lg7RW2UiBmVsU+by/1XX7+3UUgZzTcneEFHumtX2LuSqCDMoTBoqh8Cn21spZ1FjUUw89ft5pMkP4bm/2+zaAY5DN2R3SV33BbOhfjoFu8qgJ59XCYNF4q8CBRdMLj0Qa6E0ifEPtq26teA+yoHsfO8F85bgSmSOMht0GZxFMQk4fDSTrOc5D2Nu5WAnOXqmivLdyFgbcoiY5Im8ode+rbfh+zRDTmxomoRyjRWULIsve6B7seTaLTCFX7LFbg9AlAinmeVYhyFO4rMvOXYVfBQRR2B2A1jtudTe+qsny54DrW6j52ZjuIKbMzyrN1JYK2srdF+vn3gAs98aqhkJa+tKM4Qi5twL/9+2qh+LQ2P284BccfG7/wbbSLk/fdbHcZWMTg4gZd40CBlwX7oGlnFIArX4WKzMq/yzTAMnxb0FNOyUq8xDo4RcwM+gkYvJXaz3qfVPCad7kuzNhZIJL4A+c/s1LAUzvElbkaOF0PPRX3DVgpnOo8KSh21IrIT7Hh4UUfXQR34i22W+KV1S/lpvg7VVYiZtkPnZRkHVb56b1oyWM5ArELW+zZ3f18qEdq4MSG8LlGuNfqggahuY6bcOFsna1mSC924xAVBMT2KW/1r+dfu2cI3JTa9m5CBKWFXZMcDL9F0mms/j/o94=
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: geoframecomponents/LongWaveRadiationBalance
